# Generated by Django 3.1 on 2023-03-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20230328_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(default='11d8534781914e76b744edc7df7f9ba8', editable=False, max_length=200),
        ),
    ]
